POLKABOT:
  POLKADOT:
    # Polkadot config
    NODE_NAME:
      description: Name of the node we connect to. This is mainly for your documentation
      default: Node

    URL:
      mandatory: true
      description: The URL of the WebSocket to be used to connect to the node
      regexp: ^wss?:\/\/([\w-\.]+)(:(\d+))?\/?$

  MATRIX:
    # Matrix config
    BOTMASTER_ID:
      description: This is the admin of the bot
      default: '@chevdor:matrix.org'
      regexp: ^@.+:.+$

    ROOM_ID:
      description: This is the room where the Bot is active
      mandatory: true
      regexp: ^\!.+:.+$

    BOTUSER_ID:
      description: This is the Matrix account for the Bot
      mandatory: true
      regexp: ^@.+:.+$

    TOKEN:
      description: This is the Matrix secret token
      mandatory: true
      masked: true
      regexp: ^.{250,300}$

    BASE_URL:
      description: URL of the Matrix server
      mandatory: true
      default: https://matrix.org
      regexp: ^https?://.*

    LOGIN_USER_ID:
      description: Only required for custom Matrix servers
      mandatory: false
    
    LOGIN_USER_PASSWORD:
      description: Only required for custom Matrix servers
      mandatory: false
      masked: true

    MESSAGES_TO_SHOW:
      description: Number of messages to show
      default: 3
      type: number

  BLOCTHDAY:
    # Those would go to a BLOCTHDAY sub module once confmgr supports it
    DISABLED:
      description: Whether BLOCTHDAY should be enabled
      type: boolean
      default: true
      regexp: ^true|false$

    NB_BLOCKS:
      description: How often do we want to wish a happy Block-th-day. 0 disables it but many other automatic checks are done.
      type: number
      default: 0

    CHANNELS:
      description: List of notification channels
      type: array
      default: ['matrix', 'twitter']

    SPECIALS:
      description: List special (=random...) blocks we want to announce. Blocks in the past have no effect. Note that the current checkers already cover many cases such as 800000, 123456, 888888, etc....
      type: array
      default: [42, 69, 8888888]

  BLOCKSTATS:
    DISABLED:
      description: Whether BLOCKSTATS should be enabled
      type: boolean
      default: true
    
    NB_BLOCKS:
      description: How often do we calculate the stats
      type: number
      default: 100

    THRESHOLD:
      description: Number of seconds max expected between blocks
      type: number
      default: 8.0

    LOG_NTH_BLOCK:
      description: How often do we want to log
      type: number
      default: 1000

    CHANNELS:
      description: List of notification channels
      type: array
      default: ['matrix', 'twitter']

  STALLWATCHER:
    DISABLED:
      description: Whether STALLWATCHER should be enabled
      type: boolean
      default: true

    DURATION:
      type: number
      default: 15.2
    
    CHANNELS:
      description: List of notification channels
      type: array
      default: ['matrix', 'twitter']

  OPERATOR:
    DISABLED:
      description: Whether OPERATOR should be enabled
      type: boolean
      default: true

  REPORTER:
    DISABLED:
      description: Whether REPORTER should be enabled
      type: boolean
      default: true

    CHANNELS:
      description: List of notification channels
      type: array
      default: ['matrix', 'twitter']

    OBSERVED:
      description: This is the list of modules and methods we are considering
      type: object
      default: {
        democracy: ['Proposed'],
        sudo: ['Sudid'],
        treasury: ['Proposed', 'NewTip'],
        system: [],
        council: ['Executed']
      }

    BLOCK_VIEWER:
      description: The url used to see more details about a given blocks
      type: string
      default: https://ipfs.io/ipns/polkadot.dotapps.io/#/explorer/query/

  NOTIFIER_MATRIX:
    DISABLED:
      description: Whether NOTIFIER_MATRIX should be enabled
      type: boolean
      default: true

  NOTIFIER_DEMO:
    DISABLED:
      description: Whether NOTIFIER_DEMO should be enabled
      type: boolean
      default: true

  NOTIFIER_TWITTER:
    DISABLED:
      description: Whether NOTIFIER_TWITTER should be enabled
      type: boolean
      default: true

    COOLDOWN:
      descriptions: This is a value in milliseconds. We will NOT tweet again before this time elapsed.
      type: number
      default: 5000

    RATE_WINDOW:
      description: You should not change that. This window is defined by the twitter API. This is a value in milliseconds. The default is 3 hours.
      type: number
      default: 10800000

    RATE_LIMIT:
      description: This is to ensure we stay under the window limit allowed by the Twitter API. Twitter allows 300 posts per window.
      type: number
      default: 200

    CONSUMER_KEY:
      description: Twitter consumer key
      mandatory: true
      type: string
      regexp: ^.{25}$

    CONSUMER_SECRET:
      description: Twitter consumer secret
      masked: true
      mandatory: true
      type: string
      regexp: ^.{50}$

    TOKEN_KEY:
      description: Twitter App token
      mandatory: true
      type: string
      regexp: ^.{50}$

    TOKEN_SECRET:
      description: Twitter App token secret
      masked: true
      mandatory: true
      type: string
      regexp: ^.{45}$
  REPO_MONITOR:
    DISABLED:
      description: Whether REPO_MONITOR should be enabled
      type: boolean
      default: true
    TOKEN_GITHUB:
      description: Github token
      type: string
    TOKEN_GITLAB:
      description: Github token
      type: string    
    REPOS:
      description: List of repos to watch
      type: object
      default: {"github":[{"repo":"chevdor/junk1","channels":[{"type":"matrix","targets":["!fLauqijtMUNuIxxoYk:polkadot.builders","!fLauqijtMUNuIxxoYk:polkadot.builders"]},{"type":"twitter","targets":["someaccount"]}]}],"gitlab":[{"repo":"chevdor/junk1","channels":[{"type":"matrix","targets":["!fLauqijtMUNuIxxoYk:polkadot.builders","!fLauqijtMUNuIxxoYk:polkadot.builders"]},{"type":"twitter","targets":["someaccount"]}]}]}
