diff: true
extension:
  - js
  - ts
package: ./package.json
reporter: spec
slow: 75
timeout: 2000
ui: bdd
recursive: true
require:
  - ts-node/register
watch-files:
  - 'test/**/*.spec.ts'
  - 'src/**/*.ts'